In [2]:
# 필요한 모듈 불러오기
import os 
import pandas as pd

## CSV 파일 불러오기

In [169]:
tmp2 = pd.read_csv("./카카오맵_리뷰_크롤링/크롤링5_review_id/5,6호선/강남역.csv") #path 수정 필요

In [153]:
min(tmp2.review_num.tolist()) #최소 리뷰 개수

16

### 특정 음식점 DF 훑어보기

In [175]:
res_name = '을밀대 강남점' 
tmp2[tmp2.name == res_name]

,name,addresse,cat1,cat2,review_num,score_min,score,review,reviews_date,reviews_id
664,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,1,맛없어요,2022.05.24.,deneb
667,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,2,평양냉면 14000원 육수는 나쁘지 않은데 면이 맛있는지는 모르겠음 평양냉면 맛이 ...,2022.05.07.,타코
668,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,5,20년째 단골! 역시 맛있어요 ~,2022.04.30.,엔팁냠냠
669,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,5,평냉은 주기적으로 먹어줘야하니까요 강남점도 나쁘지않네요!!,2022.04.14.,냥냥펀치
670,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,3,평냉의 맛이란... 잘모르겠다 아직,2022.04.02.,맛있게먹으면0칼로리
671,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,2,장사 하고 싶지 않나보네ㅋㅋㅋ 22시까지라고 하지 말던갘ㅋㅋㅋㅋ ♬♪♪ 꼽주네 ㅡㅡ...,2022.03.15.,Y
672,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,5,을밀대 역삼점보다는 강남점이 훨씬 맛남,2022.03.13.,June
673,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,1,돈이 아까워서 육수 꾸역꾸역 먹고 면 남김 13000원이라 다 먹을려고 했는데......,2022.01.25.,김유림
674,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,2,호불호가 있을 수 있는 뭐라 말 할 수 없는 그 맛! 진정한 고기의 육수맛(?)을 ...,2021.11.25.,서의성
675,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,4,"본점보다는 부족하고, 무교점보다는 낫다.",2021.10.15.,섬나라
676,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,5,육수가 진짜 고기 육수... 막 독특하진 않지만 기본에 충실하다 못해 넘치는 매우...,2021.10.10.,백발백종원
677,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,5,3대장 평양냉면 짱마탱....수육도 먹어보고 싶어요,2021.09.11.,안주현
678,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,4,확실히 메밀향은 약하지만 육수가 걍 멱살잡고 하드캐리하는 맛. 후추향을 좋아한다면 ...,2021.08.22.,Day
679,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,4,맛있음. 육수를 아끼지 말고 많이 줬으면..ㅠㅠ,2021.08.17.,고영희
680,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,4,실패하진 않지! 비쌀뿐! 여름되니까... 진가를 발휘,2021.08.12.,관악기
681,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,5,비싸고 맛있다.. 어흐...;ㅇ; 호불호 있는맛... 녹두전도 괜춘.,2021.08.06.,yul♡
682,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,5,사랑합니다 물냉 나오면 면 흐트러뜨리지 말고 바로 국물을 먹어봐야 함 맑고 진한 소...,2021.08.05.,찌랭
683,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,3,그래도 본점,2021.07.27.,이재원
684,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,1,이것은 평양냉면이라 할 수 없다. 일반고깃집 후식냉면 급의 퀄리티,2021.07.23.,휘파람
685,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,4,을밀대는 을밀대이나 후추통이 비어도 채우지않았으며 젓가락에는 김치국물이 튀어있는걸 ...,2021.07.18.,평행주차왕 김필동
686,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,4,소문만큼 가격대비 최고는 아님,2021.07.12.,kenny
688,을밀대 강남점,서울 강남구 테헤란로4길 46 지하1층 (우)06241,냉면,"['물냉면\n14,000', '수육 (소)\n40,000', '녹두전 (1장)\n1...",150,3.2,3,"강남역에서 늦은 점심 먹게 되어 가게 된 을밀대입니다. 물냉 두 개, 녹두전 한 개...",2021.06.29.,당구

## 전처리(중복값, 결측값 drop)

In [171]:
tmp2 = tmp2.dropna(axis=0)
tmp2 = tmp2.drop_duplicates(['review','reviews_date','reviews_id'], keep='first')
limit_review_num = 100 #음식점 리뷰 개수
region_df= tmp2[tmp2['review_num'] >= limit_review_num].loc[:,['name','review']]
region_df

           name                                             review
19    백억하누 강남본점                                     푸짐하고 너무 맛있었어요~
20    백억하누 강남본점                                회식했는데 삼합 진짜 좋았습니다~~
21    백억하누 강남본점                                        맛있어요 고기질도좋고
22    백억하누 강남본점                                  친절해서 아주좋고 고기맛나요~~
23    백억하누 강남본점  고기 너무 신선하고 맛있네요.  자주 먹진 못하지만 특별한 날이나 대접하고 싶은 날...
...         ...                                                ...
1712  카페413프로젝트  가야는이유 : 오래된 가옥을 개조한듯 포근한 느낌이 있는 브런치카페 안가는이유 : ...
1713  카페413프로젝트  맛은 그닥... 분위기는 좋아요. 여자친구가 좋아해서 종종갑니다. 브런치로 프렌치토...
1716  카페413프로젝트  브런치 구성 좋고 맛있음! 분위기도 근교의 빈티지한 카페 갬성ㅎㅎ 재료 소진이 금방...
1717  카페413프로젝트                                         굳 재방문 의사 유
1718  카페413프로젝트                                               최애카페

[1022 rows x 2 columns]

In [182]:
test = pd.DataFrame()
set1 = set(region_df['name'].tolist())
res_count = 100
review_count = 50

for res in list(set1)[6:res_count+6]:
    print(res)
    region_df= tmp2.loc[:,['name','review']] # 컬럼 2개만 축출
    tmp = region_df[region_df.loc[:,'name']== res] # 특정 음식점
    first_index = region_df.index[region_df.loc[:,'name']== res][0] #인덱스 
    tmp = tmp.loc[first_index:first_index+review_count,:]
    test = pd.concat([test, tmp.loc[first_index:first_index+review_count,:]])
# 데이터 프레임의 최대 개수를 없애줍니다.
test = test.reset_index(drop=True)
# master.csv라는 파일로 만들어줍니다.
tmp.to_csv('test{0}_{1}.csv'.format(res_count,review_count), index=False)

구구당
정돈
을밀대 강남점
돝고기506
램스칸
은행골 강남역점
장꼬방
피그인더가든 강남점
왕스펍
빌리엔젤 강남역점
도치피자 강남점
어거스트힐 강남점
감성타코 강남역점
썸띵어바웃커피
비트포비아 강남던전점
아방궁
라그릴리아 SPC스퀘어점
이자카야나무 강남2호점
백억하누 강남본점
마녀주방 강남점
어글리스토브 강남역점
바비레드 강남본점
육전식당 4호점
정월
만원수산
미즈컨테이너 이스트점
갓덴스시 강남점
양파이 강남점
자매수산 1호점
창고43 강남점
육품
알부자 강남본점
마노디셰프 강남점
랑데자뷰 강남점
타르타르 강남역점
스시메이진 강남점
일일향 3호점
고메램 강남점
미즈컨테이너 강남웨스트점
국제수입식당 본점
큰물참치 강남점
해담채 강남점
베트남이랑
하이디라오 강남점
이춘복참치&스시 강남점
신동궁감자탕 역삼본점
로리스더프라임립
한성양갈비양꼬치 강남점
카페413프로젝트
요멘야고에몬 강남점
농민백암왕순대
조양관
원조부안집 강남점
스시마이우 강남CGV점
강남진해장
낙원타코 강남역점
비어룸
빌즈 강남
60년전통신촌황소곱창 강남직영점
우동명가 기리야마본진
아트몬스터 강남역점
이자카야나무 강남3호점
라공방 강남1호 본점
장인닭갈비 강남점
남도애찬
무월 강남점
알베르

In [183]:
test

     name                                             review
0     구구당                                홍콩파스타 샐러드 딴딴어쩌구 대존맛
1     구구당  맛 자체는 있는데, 가성비가 너무 떨어지고 매장 이용하다보면 좀 '괘씸하다'라는 느...
2     구구당                                 음식은 맛있는데 직원이 싸가지없음
3     구구당  맛이었어요, 근대,홀 서빙을 찐자 재수없어요   분명히 웨이터에게 식사를 추가하자고...
4     구구당                                     꿔바로우 노맛이에요 ㅠㅠ
...   ...                                                ...
1231  알베르                                           매장 예뻐요^^
1232  알베르  인테리어 좋고 분위기 좋구 시끄럽지 않아서 좋아요. 커피는 무난한듯. 얼그레이 파운...
1233  알베르  별로에요. 브라우니 진짜...너무 푸석함.... 메마른 부라우니를 팔다니....  ...
1234  알베르                        매장이 넓고 분위기는 좋은데. 비싸고 불친절 ㅡㅡ
1235  알베르                 강남 카페 분위기랑 다르게 분위기가 여유롭구 커피도 맛있어요

[1236 rows x 2 columns]